version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - chmod +x gradlew
      - ./gradlew bootWar
      - mv build/libs/*.war ./
artifacts:
  files:
    - ./*.war


  discard-paths: yes
