version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  post_build:
    commands:
      - gradlew package
      - mv target/hms-0.0.1-SNAPSHOT.war hms-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - hms-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*
  base-directory: 'build/libs'